<?php
// $Id$

/**
 * @file
 * Allows to use PHP in views.
 */

/**
 * Implements hook_views_api().
 */
function views_php_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Menu access callback function; use PHP code to determine whether a user as
 * access.
 */
function views_php_check_access($php_access, $view_name, $display_id, $account = NULL) {
  global $user;
  static $lamda_function = array();

  if (!isset($account)) {
    $account = $user;
  }

  if (!isset($lamda_function[$view_name . ':' . $display_id])) {
    $lamda_function[$view_name . ':' . $display_id] = create_function('$view_name, $display_id, $account', $php_access);
  }

  ob_start();
  $access = (bool) $lamda_function[$view_name . ':' . $display_id]($view_name, $display_id, $account);
  ob_end_clean();
  return $access;
}

/**
 * Helper function; only users with use PHP permission can provide input for given element.
 */
function views_php_check_input_access(&$element) {
  if (!user_access('use PHP for settings')) {
    $element['#disabled'] = TRUE;
    $element['#value'] = $element['#default_value'];
    $element['#description'] .= ' <strong>' . t('Note: you do not have permission to modify this.') . '</strong>';
  }
}

/**
 * Helper function; only users with use PHP permission can provide input for given element.
 */
function views_php_available_variables(&$element, $view, $handler, $variables = array()) {
  $defaults = array(
    '$view'    => t('The view object.'),
    '$handler' => t('The handler object.'),
    '$row'     => t('Contains the retrieved record from the database (e.g. $data->nid).'),
    '$data'    => t('Contains the retrieved record from the database (e.g. $data->nid).'),
    '$results'  => t('Array containing the view\'s result.'),
    '$static'  => t('A variable that can be used to store reusable data per row.'),
  );

  $items = array();
  foreach ($variables as $name => $description) {
    if (is_int($name) && isset($defaults[$description])) {
      $items[] = l($description, '', array('fragment' => $element['#id'], 'external' => TRUE)) . ': ' . $defaults[$description];
      if ($description == '$row') {
        foreach ($view->display_handler->get_handlers('field') as $field => $handler) {
          $items[] = l('$row->' . $field, '', array('fragment' => $element['#id'], 'external' => TRUE)) . ': ' . $handler->ui_name();
        }
      }
    }
    else {
      $items[] = l($name, '', array('fragment' => $element['#id'], 'external' => TRUE)) . ': ' . $description;
    }
  }

  $fieldset = array(
    '#type' => 'fieldset',
    '#title' => t('Available variables'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('class' => array('views-php-variables')),
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'views_php') . '/views_php.js'),
    )
  );
  $fieldset['variables'] = array(
    '#theme' => 'item_list',
    '#items' => $items,
  );

  return $fieldset;
}

/**
 * Implements hook_views_pre_execute().
 */
function views_php_views_pre_execute($view) {
  // Seize control over the query plugin if a views handler requested so.
  if (!empty($view->views_php)) {
    $query = new views_php_plugin_query();
    $query->php_wrap($view->query);
  }
}

/**
 * Implements hook_views_post_execute().
 */
function views_php_views_post_execute($view) {
  // Restore original query plugin if it was wrapped.
  if ($view->query instanceof views_php_plugin_wrapper) {
    $view->query->php_unwrap();
  }
}
